### ISSUE TITLE
Delineate compatibility Strapi v3.x and v4

### ISSUE THREAD

**Issue by lack-of-gravitas** [strapi/awesome-strapi#54]
A large number of these plugins / references are now not compatible with Strapi v4 release. **This makes it no longer awesome-strapi** -- 

(super sad face)

**Comment by ChristianHeimke** [comment]
maybe we can add some tags like awesome nuxt did for tutorials: https://github.com/nuxt-community/awesome-nuxt#tutorials a bunch of projects still use v3 in production and long term projects... they should be still present for others.

**Comment by derrickmehaffy** [comment]
For v4 stuff we are recommending everyone to use this community maintained website instead (which is powered by Strapi v4):

https://isstrapiready.com
